[package]
name = "dua-cli"
version = "2.1.10"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
edition = "2018"
include = ["src/**/*", "Cargo.toml"]
repository = "https://github.com/Byron/dua-cli"
readme = "README.md"
description = "A tool to conveniently learn about the disk usage of directories, fast!"
license = "MIT"

[dependencies]
failure = "0.1.1"
failure-tools = "4.0.2"
structopt = "0.2.14"
jwalk = "0.4.0"
byte-unit = "3"
termion = "1.5.2"
atty = "0.2.11"
tui = "0.6.0"
petgraph = "0.4.13"
itertools = "0.8.0"
open = "1.2.2"
log = "0.4.6"
tui-react = { path = "./tui-react", version = "0.1" }
num_cpus = "1.10.0"
unicode-segmentation = "1.3.0"

[[bin]]
name="dua"
path="src/main.rs"

[lib]
name="dua"

[profile.release]
panic = 'unwind'
incremental = false
overflow-checks = false
lto = true

[dev-dependencies]
pretty_assertions = "0.6.1"

[workspace]
members = ["tui-react"]
