[package]
name = "dua-cli"
version = "2.10.7"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
edition = "2018"
repository = "https://github.com/Byron/dua-cli"
readme = "README.md"
description = "A tool to conveniently learn about the disk usage of directories, fast!"
license = "MIT"
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md", "!**/*_test/*"]

[features]
default = ["tui-crossplatform"]
tui-unix = ["crosstermion/tui-react-termion", "tui-shared"]
tui-crossplatform = ["crosstermion/tui-react-crossterm", "tui-shared"]

tui-shared = ["tui", "tui-react", "open", "unicode-segmentation"]

[dependencies]
clap = "3.0.0-beta.2"
jwalk = "0.5.0"
byte-unit = "4"
atty = "0.2.11"
petgraph = "0.5"
itertools = "0.10.0"
num_cpus = "1.10.0"
filesize = "0.2.0"
anyhow = "1.0.31"
colored = "2.0.0"

# 'tui' related
unicode-segmentation = { version = "1.3.0", optional = true }
crosstermion = { optional = true, version = "0.5.0", default-features = false }
tui = { version = "0.13.0", optional = true, default-features = false }
tui-react = { version = "0.13", optional = true }
open = { version = "1.2.2", optional = true }
wild = "2.0.4"

[[bin]]
name="dua"
path="src/main.rs"

[lib]
name="dua"

[profile.release]
panic = 'abort'
incremental = false
overflow-checks = false
lto = "fat"
codegen-units = 1
build-override = { opt-level = 0 }

[dev-dependencies]
pretty_assertions = "0.6.1"

[workspace]
members = ["tui-react"]
